trigger:
  - master

pool:
  vmImage: 'windows-latest'
  
variables:
  buildConfiguration: 'Release'
  
steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      restoreDirectory: '$(System.DefaultWorkingDirectory)'
      #packDirectory: '$(System.DefaultWorkingDirectory)'
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
    displayName: 'dotnet build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/*Test/*.csproj'
      arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
