trigger:
  - master

pool:
  vmImage: 'windows-latest'
  
variables:
  buildConfiguration: 'Release'
  
steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      restoreDirectory: '$(System.DefaultWorkingDirectory)'
      #packDirectory: '$(System.DefaultWorkingDirectory)'
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
    displayName: 'DotNet Build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*Test/*.csproj'
      arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
    displayName: 'DotNet Test Build'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      arguments: '--configuration $(buildConfiguration)'
      outputDir: '$(System.DefaultWorkingDirectory)\MessageUtil\bin\Release\netcoreapp3.1\publish\'
    displayName: 'DotNet Publish Build'

  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)\ziping.ps1
      errorActionPreference: 'stop'
    
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(System.DefaultWorkingDirectory)\MessageUtil.zip
      artifactName: MessageUtil
