trigger:
  - master

pool:
  vmImage: 'windows-latest'
  
variables:
  buildConfiguration: 'Release'
  runtimeIdentifier: 'win10-x64'
  selfContained: true
  useAppHost: true
  
steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      restoreDirectory: '$(System.DefaultWorkingDirectory)'
      #packDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'DotNet Restore Project'
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
    displayName: 'DotNet Build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*Test/*.csproj'
      arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
    displayName: 'DotNet Test Build'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      arguments: '--configuration $(buildConfiguration) -r $(runtimeIdentifier) --self-contained $(selfContained) --UseAppHost $(useAppHost)'
      zipAfterPublish: false
    displayName: 'DotNet Publish Build'

  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)\ziping.ps1
      errorActionPreference: 'stop'
    displayName: 'DotNet Zip Publish'
    
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(System.DefaultWorkingDirectory)\MessageUtil.zip
      artifactName: MessageUtil
    displayName: 'Upload Zip'